import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Link from "next/link";
import "./globals.scss";
import { User, Search, ShoppingCart } from "lucide-react";

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  variable: "--Montserrat",
});

export const metadata: Metadata = {
  title: "PC-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <nav className="flex bg-white text-black p-4 gap-4 items-center">
          <Link href="/" className="text-xl font-bold">
            PC-Shop
          </Link>
          <Link href="/laptops"> Laptops </Link>
          <Link href="/desktopPCs"> Desktop PCs </Link>
          <Link href="/partsPC"> PC Parts </Link>
          <Link href="/others"> All Others Products </Link>
          <div className="relative flex items-center">
            <input
              type="text"
              className="border rounded px-3 py-1 pl-10 focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Search"
            />
            <Search className="absolute left-3 h-5 w-5 text-gray-500" />
          </div>
          <Link href="/cart" className="flex">
            <ShoppingCart className="h-5 w-5" />
          </Link>
          <Link href="/loginPage" className="flex items-center gap-1">
            <User className="h-5 w-5" />
            <span> Sign In </span>
          </Link>
        </nav>
        {children}
        <footer className="info-footer">
          <p className="info-copyright">
            © 2025 Erik Sodel. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
